"""Rename student column

Revision ID: 489895a8d707
Revises: 791279dd0760
Create Date: 2023-09-09 10:17:25.252147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489895a8d707'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('contact_info', sa.String(length=55), nullable=True))
    op.add_column('students', sa.Column('new_column_name', sa.String(length=100), nullable=True))
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=55), nullable=True))
    op.drop_column('students', 'new_column_name')
    op.drop_column('students', 'contact_info')
    # ### end Alembic commands ###
